### PR TITLE
Support oneOf w/ discriminator

### LINKED ISSUE #593: Support discriminator in oneOf
**Is your feature request related to a problem? Please describe.**
Per [OAS spec](https://spec.openapis.org/oas/latest.html#discriminator-object) (also see [Swagger docs](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof)), discriminator support is needed.

**Describe the solution you'd like**
See unit test in pull request #594 

**Describe alternatives you've considered**
n/a

**Additional context**

### PR DESCRIPTION
**Pull request by westse**
**What**: Adds support for discriminator per [OAS spec](https://spec.openapis.org/oas/latest.html#discriminator-object). NOTE unit test depends on #585 having been fixed.

**Why**: To fix issue #593 and add discriminator support per OAS spec.

**How**: Enhanced existing allOf support

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [X] Tests
- [ ] Sonar Quality Gate

**Issue ID**:
Closes: #593

NOTE unit test depends on #585 having been fixed

### CODE REVIEW

**Comment by joelrosario** [comment]
@westse #585 has been fixed. However, we noticed that the PR title mentions support for discriminator with allOf. However, the [OpenAPI documentation](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) indicates that the discriminator is supported only with oneOf and anyOf. In the case of allOf, the discriminator does not have a role to play as we cannot pick one among the given specifications. allOf is fully inclusive, as all the given specifications provided must be adhered to.

You could add support for the discriminator in oneOf.

**Comment by westse** [comment]
@joelrosario Thanks - yes, I should not have mentioned allOf. I have changed the titles of this PR and issue #593 , and this PR should be good to merge.

**Review by harikrishnan83 — APPROVED** [review]
Looks good to me

**Comment by harikrishnan83** [comment]
@westse Thanks for this Pull Request. Appreciate it very much. cc @joelrosario

**Comment by joelrosario** [comment]
Hi @westse, we recently had occasion to check the OpenAPI documentation on discriminator again, and it seems to be saying that `discriminator` belongs as a sibling key to oneOf.

Here's a sample specification that has the discriminator where it should be according to the documentation, from what we can see.

```yaml
---
openapi: "3.0.1"
info:
  title: "Test"
  version: "1"
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              ${'$'}ref: "#/components/schemas/Pet_Polymorphic"
      responses:
        "200":
          description: "updated"
          content:
            text/plain:
              schema:
                type: "string"
components:
  schemas:
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
    Pet_Polymorphic:
      oneOf:
        - ${'$'}ref: '#/components/schemas/Cat'
        - ${'$'}ref: '#/components/schemas/Dog'
      discriminator:
        propertyName: pet_type
    Dog:
      allOf:
      - ${'$'}ref: '#/components/schemas/Pet'
      - type: object
        properties:
          bark:
            type: boolean
          breed:
            type: string
            enum: [Dingo, Husky]
    Cat:
      allOf:
      - ${'$'}ref: '#/components/schemas/Pet'
      - type: object
        properties:
          hunts:
            type: boolean
          age:
            type: integer
```

And here's a sample specification showing where it has to be today per our implementation:

```yaml
---
openapi: "3.0.1"
info:
  title: "Test"
  version: "1"
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              ${'$'}ref: "#/components/schemas/Pet_Polymorphic"
      responses:
        "200":
          description: "updated"
          content:
            text/plain:
              schema:
                type: "string"
components:
  schemas:
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Pet_Polymorphic:
      oneOf:
        - ${'$'}ref: '#/components/schemas/Cat'
        - ${'$'}ref: '#/components/schemas/Dog'
    Dog:
      allOf:
      - ${'$'}ref: '#/components/schemas/Pet'
      - type: object
        properties:
          bark:
            type: boolean
          breed:
            type: string
            enum: [Dingo, Husky]
    Cat:
      allOf:
      - ${'$'}ref: '#/components/schemas/Pet'
      - type: object
        properties:
          hunts:
            type: boolean
          age:
            type: integer
```

I've been playing with a change that implements it the way we see it in the documentation. [Here's the PR](https://github.com/znsio/specmatic/pull/667).

We would like to have your thoughts on this,

**Pull request merged**
