### PR TITLE
Fetch auth tokens from both environment and settings

### PR DESCRIPTION
**Pull request by androa**
This makes it possible to create a token before running tests with SpecmaticJUnitSupport

**What**: Look for auth tokens in both environment and settings

**Why**: I want to be able to create tokens at runtime, before running contract tests with `SpecmaticJUnitSupport`

**How**: Use the getter that checks both environment and settings.

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [ ] Tests
- [ ] Sonar Quality Gate

**Issue ID**:
Closes: #123

### CODE REVIEW

**Review by joelrosario — APPROVED** [review]
Thanks @androa for this PR. Looks good to me. I am merging it, and it will be available soon.

**Comment by androa** [comment]
Thanks for the quick response @joelrosario 🚀 I haven't really used Specmatic since version 0.77, but I must say it was a much nicer experience this time! Had both a stub server and contract tests running in no time!

**Comment by noelmccrory** [comment]
With this change, does it mean that I should be able to set:

`System.setProperty("BearerAuth", "abcdef");`

when my API Spec contains:

```
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```

I'm not able to get this working. 

My understanding is that Specmatic should automatically create a dummy Authorization header on requests without setting any properties / environment variables, but it is not even doing that. I've also tried various ways of setting environment variables, but still doesn't result in any authorization headers getting included on the request. 

Any ideas? 

I am using 1.3.11 which includes the changes in this PR.

Thanks.

**Comment by yogeshnikam671** [comment]
Hey @noelmccrory, we have created an [issue](https://github.com/znsio/specmatic/issues/1072) to track the problem that you are facing.
We can collaborate over there to resolve your issue. Thanks.

**Pull request merged**
